Address EditorConfig violations (#5816)
Signed-off-by: Michael Baumgartner <Michael-Baumgartner@posteo.de>

diff --git a/.github/actions/run-gradle/action.yml b/.github/actions/run-gradle/action.yml
--- a/.github/actions/run-gradle/action.yml
+++ b/.github/actions/run-gradle/action.yml
@@ -39,21 +39,21 @@ runs:
         "-Dscan.value.GitHub job=${{ github.job }}" \
         javaToolchains \
         ${{ inputs.arguments }} || error_code=$?
-        
-        
+
+
         if [ -n "${{ inputs.broken-by-issue }}" ]; then
           if [ -n "$error_code" ]; then
-            # we expected the build to fail, it failed => pass 
+            # we expected the build to fail, it failed => pass
             exit 0
-          else            
+          else
             # we expected the build to fail, it didn't => fail
             RED='\033[0;31m'
             RESET='\033[0m' # No Color
             echo "${RED}Build was expected to fail, but it passed. Was ${{ inputs.broken-by-issue }} resolved?${RESET}"
-            exit 1            
+            exit 1
           fi
         fi
-        
+
         # exit with the original error code if set
         if [ -n "$error_code" ]; then
           exit "$error_code"
